### ISSUE TITLE
bug: Crash on new update, 3.6.0 Mac

### ISSUE THREAD

**Issue by vlad-cotfas** [quanglam2807/singlebox#261]
I`ve just updated to 3.6.0 and I can no longer start the app.

It gives me an error:

Uncaught Exception:
Error: Cannot find module 'core-js/modules/es.symbol'
Require stack:
- /Applications/Singlebox.app/Contents/Resources/app.asar/node_modules/@jimp/custom/dist/index.js
- /Applications/Singlebox.app/Contents/Resources/app.asar/node_modules/jimp/dist/index.js
- /Applications/Singlebox.app/Contents/Resources/app.asar/build/libs/workspaces.js
- /Applications/Singlebox.app/Contents/Resources/app.asar/build/listeners/index.js
- /Applications/Singlebox.app/Contents/Resources/app.asar/build/electron.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7630:16)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Applications/Singlebox.app/Contents/Resources/app.asar/node_modules/@jimp/custom/dist/index.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)

**Comment by vlad-cotfas** [comment]
I`ve downgraded back to 3.5.2
